language: python

python:
  - "3.4"
  - "2.7"
  - "2.6"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - "pip install -r requirements.txt"
  - "pip install -r requirements/test.txt"

script: make test

after_success:
  - coveralls
